apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: volume
  namespace: argocd
spec: 
  destination: 
    namespace: volume-pv-namespace
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: directory
    repoURL: "https://github.com/adrabenche/my-argocd-examples.git"
    targetRevision: master
    directory:
      recurse: true
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
