---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: cardano-pod
  namespace: argocd
spec: 
  destination: 
    namespace: cardano-namespace
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: cardano-db-sync
    repoURL: "https://github.com/adrabenche/my-argocd-examples.git"
    targetRevision: prometheus
    directory:
      recurse: true
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: prometheus
  namespace: argocd
spec: 
  destination: 
    namespace: monitoring
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    repoURL: "https://github.com/prometheus-community/helm-charts.git"
    targetRevision: main
    path: charts/kube-prometheus-stack/
    helm:
      releaseName: prometheus-test-1
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: prometheus-zalando-exporter
  namespace: argocd
spec: 
  destination: 
    namespace: cardano-namespace
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    repoURL: "https://github.com/zalando/postgres-operator.git"
    targetRevision: master
    path: charts/postgres-operator/
    helm:
      releaseName: prometheus-test-1
  syncPolicy:
    syncOptions:
      - CreateNamespace=true