---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: prometheus-operator
  namespace: argocd
spec: 
  destination: 
    namespace: monitoring
    server: "https://kubernetes.default.svc"
  project: monitoring
  source: 
    path: charts/kube-prometheus-stack
    repoURL: "https://github.com/prometheus-community/helm-charts.git"
    targetRevision: main
    helm:
      releaseName: prometheus-operator-v1
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
---
