apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: req-limit
  namespace: argocd
spec: 
  destination: 
    namespace: req-limit
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: Manifests/requests-limits
    repoURL: "https://github.com/adrabenche/my-argocd-examples.git"
    targetRevision: projects
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
