apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: vault-app
  namespace: argocd
spec: 
  destination: 
    namespace: vault
    server: "https://kubernetes.default.svc"
  project: vault
  source: 
    path: .
    repoURL: "https://github.com/hashicorp/vault-helm.git"
    targetRevision: v0.23.0
    helm:
      releaseName: vault-cluster
      parameters:
        - name: server.ha.enabled
          value: "false"
  syncPolicy:
    syncOptions:
      - CreateNamespace=true