apiVersion: v1
kind: Service
metadata:
 name: hello-service-np
 namespace: hello-namespace
spec:
 type: NodePort
 selector:
   app: hello
 ports:
 - protocol: TCP
   port: 80
   targetPort: 8080
   nodePort: 30000
