# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: pv-lbsr-rw
#   namespace: volume-pv-namespace
# spec:
#   storageClassName: linode-block-storage-retain
#   capacity:
#     storage: 5Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
#   csi:
#     driver: linodebs.csi.linode.com
#     volumeHandle: <linode_volume_label>
#     readOnly: false
#     fsType: ext4