---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-lbsr-rw
  namespace: volume-pv-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: linode-block-storage-retain
