---
# Service
apiVersion: v1
kind: Service
metadata:
  name: cardano-node-service
  namespace: cardano-namespace
spec:
  selector:
    app: cardano-node
  type: ClusterIP
  ports:
  - name: cardano-node-ports
    protocol: TCP
    port: 8080
    targetPort: 80

---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cardano-node-deployment
  namespace: cardano-namespace
  labels:
    app: cardano-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cardano-node
  template:
    metadata:
      labels:
        app: cardano-node
    spec:
      containers:
      - name: cardano-postgres-container
        image: gcr.io/google-samples/hello-app:2.0
        resources:
          limits:
            cpu: "500m"
