apiVersion: v1
kind: Service
metadata:
 name: hello-service-np
 namespace: hello-nginx
spec:
 type: NodePort
 selector:
   app: hello
 ports:
 - protocol: TCP
   port: 8080
   targetPort: 80
   nodePort: 30010
