apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  namespace: hello-nginx
spec:
  selector:
    matchLabels:
      app: hello
  replicas: 3
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: nginx:1.23.1
          env:
            - name: POD_NODE
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
         
      
