---
apiVersion: v1
kind: Service
metadata:
  name: service-loadbalancer-volume
  namespace: volume-pv-namespace
spec:
  type: LoadBalancer
  selector: 
    app: loadbalancer 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
